### ISSUE TITLE
[Epic] Training User Experience

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#1475]
- [ ] Implement parallel multi-checkpoint evaluation w/ eval team via CLI
- [ ] Design + implement "Orchestrated" multi-phase training (systemd?)
- [ ] identify range of recoverable / irrecoverable states that can occur during training
- [ ] FlashAttention disable support
