### ISSUE TITLE
[Epic] Improvements and fixes to `ilab` logging

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/instructlab#2186]
We have many issues related to logging, this epic can be used to encompass them all

Issues in this Epic:
- [x] #1720
- [x] #2080 
- [x] https://github.com/instructlab/instructlab/issues/1738
- [ ] https://github.com/instructlab/instructlab/issues/1290
- [x] https://github.com/instructlab/instructlab/issues/2258

**Comment by nathan-weinberg** [comment]
Partially complete, no longer be actively used to track logging issues - closing
