### ISSUE TITLE
[Epic] Improvements to E2E testing

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/instructlab#2196]
This issue is meant to track related smaller issues aiming to improve our E2E testing infrastructure and coverage matrix

Issues in this epic:

- [x] #1806 
- [x] #2197
- [x] https://github.com/instructlab/instructlab/issues/1112
- [x] https://github.com/instructlab/instructlab/issues/1599
- [ ] https://github.com/instructlab/instructlab/issues/1638
- [x] https://github.com/instructlab/instructlab/issues/1642
- [x] https://github.com/instructlab/instructlab/issues/1771
- [x] https://github.com/instructlab/instructlab/issues/2227
- [x] https://github.com/instructlab/instructlab/issues/2228
- [x] https://github.com/instructlab/instructlab/issues/2229
- [x] https://github.com/instructlab/instructlab/issues/1970
- [x] https://github.com/instructlab/instructlab/issues/1655
- [x] https://github.com/instructlab/instructlab/issues/2360
- [ ] https://github.com/instructlab/instructlab/issues/2417
- [x] https://github.com/instructlab/instructlab/issues/2420
- [x] https://github.com/instructlab/instructlab/issues/2427
- [x] https://github.com/instructlab/instructlab/issues/2429
- [x] https://github.com/instructlab/instructlab/issues/2430
- [ ] https://github.com/instructlab/instructlab/issues/2496
- [ ] https://github.com/instructlab/instructlab/issues/2570
- [ ] https://github.com/instructlab/instructlab/issues/2614
- [x] https://github.com/instructlab/instructlab/issues/2737
- [x] https://github.com/instructlab/instructlab/pull/1609

**Comment by nathan-weinberg** [comment]
Superceded by https://github.com/instructlab/instructlab/issues/3030
