### ISSUE TITLE
[Epic] Community Training Redesign

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#2230]
Current Issues

- linux_train.py is not maintained
- linux_train.py uses SFTTrainer
- MLX Code is not maintained and out of date
- `ilab model convert` is finicky as of 0.18.0

The training library doesn't support CPU, MLX, or MPS meaning that laptop users need to use `--legacy` or the MLX code. Both of these should be removed and/or rewritten.

For CPU, the `--legacy` code should be re-written to use torchrun and a custom training loop using a `LLamaForCausalLM` model. This should use as many utils directly from the training library as necessary. The training loop will be different though to be optimized to work on CPU and MPS (more storage efficient optimizers, no DeepSpeed)

For MacOS add MPS support and re-write MLX support. MPS is good to have as users can produce a .bin model and use a torch training loop. However, MLX is often faster and better maintained by Apple, so we must support this as well and allows users to switch between these implementations

so a few tasks

- [ ]  write torchrun_train.py for CPU and MPS support
- [ ]  rewrite MLX code
- [ ]  remove `--legacy` and `linux_train.py`
- [ ]  create training profiles for CPU, MPS so the UX is the same for the library and the CPU/MPS train loop to be in ilab
- [ ]  ultimately move the community training loop to instructlab/training when the library can support it.
