### ISSUE TITLE
[Epic] Granite 8B Support - cross component checkist

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#2483]
Epics Needed:

CLI:
- [x] instructlab/instructlab#2510
- [x] instructlab/instructlab#2550
- [x] Assess conversion to gguf with llama cpp for 8b model

Training:
- [x] Update the InstructLab training library to support the GraniteHFModel class - https://github.com/instructlab/training/pull/257
- [x] https://github.com/instructlab/instructlab/pull/2474
- [x] instructlab/training#287
- [x] instructlab/training#288
- [x] instructlab/training#289
- [x] instructlab/training#310

**Comment by ktam3** [comment]
@cdoern @Maxusmusti @danmcp - please use this tracker for the epics/tasks needed for this feature

**Comment by ktam3** [comment]
Update:

- Synced with Charlie and Mustafa wrt the work needed to complete this feature and created new issues in the CLI and Training libraries to track that work for Sprint 3

cc. @danmcp @cdoern @Maxusmusti
