### ISSUE TITLE
[Epic] Tech Preview ‘support’ for Gaudi 3

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#2484]
Note:
- We will be supporting granite 7b models for this Tech Preview, since the Gaudi software version we're supporting is 1.18, and will not have the granite class support

Tasks Needed

Training
- [x] instructlab/instructlab#2364 
- [x] Sync w. Platform and intel team
- [x] Working w/ intel to get this to a functional state

CLI
- [x] instructlab/instructlab#2511
     - [x] Profiles support for FSDP changes 
     - [x] vllm version bump #2528 
- [x] instructlab/instructlab#2437

Docs
- [x] Provide Kelly complete feature
