### ISSUE TITLE
[Epic] Phase 1: Custom Skills - Validate what currently works without code changes (cross team tracker)

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#2561]
Phase 1: Verify what currently works for custom skills

CLI: n/a

Training: 

- [ ] Get information on pre computed data sets for 8B
   - [ ] If it overshadows new skills, we need to develop a minimum set of precomputed data to use when skills are added
   - [ ] If it doesn't overshadow new skills, should be good to go

SDG:

- [ ] - verifying if the skills we support currently actually works
- [ ] - test training effectiveness with the skills
- [ ] - test if custom skills works on skills, knowledge and both together.
