### ISSUE TITLE
Intel Gaudi 3 Support - Cross Team Tracker 

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#2623]
**CLI Epics**
- [ ] System Profile for Intel Gaudi 3
- [ ] Auto detection for Intel Gaudi 4

**Training Epics**
- [ ] Train classes and compute graph considerations
