### ISSUE TITLE
Add Python coding style

### ISSUE THREAD

**Issue by hickeyma** [instructlab/instructlab#77]
It is imperative to follow a coding style like python [pep8](https://peps.python.org/pep-0008/) to ensure good coding practises. 

The work can be broken down into the following parts:

- [x] Add linting tool (suggestion [pylint](https://pylint.readthedocs.io/en/stable/)) (#78)
- [x] Enable linting in CI/CD (PR will fail until the style has been applied correctly)(#85)
- [x] Add formatters (tools that automatically format your code according to a set of rules or style guides) (suggestion:  [black](https://github.com/psf/black) and [isort](https://pycqa.github.io/isort/)(#107)
- [x] Enable formatters in CI/CD (PR will fail until the style has been applied correctly)(#120)
- [x] Add [tox](https://tox.wiki/en/4.12.1/) which is a generic virtual environment management and test command line tool that can also manage performing linting and formatting. It can be used for the unit testing also. (#78)
- [x] Add contributor doc (add when enabling CI/CD) (#85)(#121)
