### ISSUE TITLE
EPIC: improve `ilab` output quality

### ISSUE THREAD

**Issue by mairin** [instructlab/instructlab#869]
This epic tracks issues related to improving the quality of `ilab` synthetic data generation:

- [x] https://github.com/instruct-lab/cli/issues/826
- [x] https://github.com/instruct-lab/cli/issues/851
- [x] https://github.com/instruct-lab/cli/issues/853
